### ISSUE TITLE
Integration breaks if AirCo is in the Dual Power fan mode

### ISSUE THREAD

**Issue by Evil-Crab** [danielrivard/homeassistant-innova#199]
**Describe the bug**
Integration does not support Dual Power mode and breaks if it's selected via remote or touchscreen

**To Reproduce**
Set Innova 2.0 airco to heating or cooling mode
Set fan speed to Dual Power mode via remote or touchscreen
Reload integration

**Expected behavior**
Integration should support Dual Power mode

**Log**
`2024-05-26 13:46:36.084 ERROR (MainThread) [homeassistant.components.climate] Error adding entity climate.living_room_airco for domain climate with platform innova
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 892, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1359, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1009, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
    if state_attributes := self.state_attributes:
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 542, in state_attributes
    data[ATTR_FAN_MODE] = self.fan_mode
                          ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/innova/climate.py", line 216, in fan_mode
    current_mode = self.coordinator.innova.fan_speed
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/innova_controls/innova.py", line 127, in fan_speed
    return self._innova_device.fan_speed
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/innova_controls/twopointzero.py", line 75, in fan_speed
    return self.fan_speeds[self._status["fs"]]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 4`

**Comment by Evil-Crab** [comment]
I think Dual Power mode should map to `FAN_TOP` from `homeassistant.components.climate.const`

**Comment by danielrivard** [comment]
Good catch! I rarely use this fan mode. 

Thanks for the easy steps to reproduce, got it reproduced on the first try.

I'll look into fixing this soon.

**Comment by danielrivard** [comment]
After looking at it, I now remember why I didn't include this fan speed in the code. 

It's because it is not modifiable through the API, only via the remote or the LCD like you found out. So in Home Assistant it would need to be a fan speed that cannot be set, only for display purposes.

Not sure how I will fix this yet.
The best option I see so far would be Add this fan speed (FAN_TOP) and if it is set by the remote or lcd, display it in the entity card as the selected fan speed. If the user chooses this fan mode, just set the value as FAN_HIGH instead. 

But that might create confusion and look like a bug.
