### ISSUE TITLE
I Get a error with the latest 0.3 version

### ISSUE THREAD

**Issue by sander2506** [danielrivard/homeassistant-innova#9]
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:679
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 12:29:49 (2 occurrences)
Last logged: 12:30:35

[547436192288] The system cannot restart because the configuration is not valid: Platform error climate.innova - No module named 'retry'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 189, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 679, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error climate.innova - No module named 'retry'
```
```
Logger: homeassistant.config
Source: custom_components/innova/climate.py:31
Integration: innova ([documentation](https://github.com/danielrivard/homeassistant-innova/blob/main/README.md), [issues](https://github.com/danielrivard/homeassistant-innova/issues))
First occurred: 12:07:55 (1 occurrences)
Last logged: 12:07:55

Platform error: climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 603, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 620, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/innova/climate.py", line 31, in <module>
    from innova_controls import Innova, Mode
  File "/usr/local/lib/python3.9/site-packages/innova_controls.py", line 5, in <module>
    from retry import retry
ModuleNotFoundError: No module named 'retry'
```

**Comment by danielrivard** [comment]
Oh, sorry about that, I forgot to add a library to the manifest. I will update and create version 0.0.4.

That also means I will need to add tests to this project, now that others than me use it.

**Comment by danielrivard** [comment]
0.0.4 is released. That should fix the problem. Let me know if it does not.

**Comment by sander2506** [comment]
> 0.0.4 is released. That should fix the problem. Let me know if it does not.

Yes it's working, thnx.
